{{- $fullName := include "contacts-app.fullname" . -}}
{{- $appName := include "contacts-app.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
{{- if .Values.cmdb }}
  namespace: {{ .Values.nameSpace }}
{{- end }}
  labels:
    app: {{ $appName }}
    chart: {{ template "contacts-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.cmdb }}
  {{- range $key, $value := .Values.manifestValues }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.tiller }}
{{- if .Values.postgresql.enabled }}
    ATLAS_DATABASE_HOST: {{ template "contacts-app.postgresql.fullname" . }}
    ATLAS_DATABASE_NAME: {{ .Values.postgresql.postgresDatabase }}
    ATLAS_DATABASE_USER: {{ .Values.postgresql.postgresUser }}
{{- end }}
{{- end }}
