{{- $fullName := include "contacts-app.fullname" . -}}
{{- $appName := include "contacts-app.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
{{- if .Values.cmdb }}
  namespace: {{ .Values.nameSpace }}
{{- end }}
  labels:
    app: {{ $appName }}
    chart: {{ template "contacts-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $appName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{template "imagespec" dict "containers" .Values.containers "containername" "contacts-app"}}
          imagePullPolicy: {{template "imagepull" dict "containers" .Values.containers "containername" "contacts-app"}}
          envFrom:
          - configMapRef:
              name: {{ $fullName }}
          env:
{{- if .Values.postgresql.enabled }}
            - name: ATLAS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "contacts-app.postgresql.fullname" . }}
                  key: postgres-password
{{- end }}
            - name: "ATLAS_LOG_LEVEL"
              value: {{ .Values.logLevel }}
          image: soheileizadi/contacts-server:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8081
            protocol: TCP
          - containerPort: 9090
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
